name: 'Claude Assisted Code Review - FORK'
description: 'Use claude to perform assisted code reviews.'
author: 'small3flower'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
inputs:
  github_token:
    description: 'github token'
    required: true
  anthropic_api_key:
    description: 'Anthropic API key'
    required: true
  model_name:
    description: 'Claude model name'
    default: 'claude-3-5-sonnet-20241022'
  model_temperature:
    description: 'Claude model temperature'
    default: '0'
  exclude_files:
    description: 'Provide a wildcard expression to exclude files from code review. For example, `*.md` will exclude all markdown files. Multiple expressions are supported via commas, eg `*.js, *.cjs`'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
